### ISSUE TITLE
The version number for WordPress compatibility needs to be changed

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/woocommerce-delivery-date#10]
Current WordPress compatibility is set to 4.2.5 so while updating the plugin or viewing the plugin details from the Plugins page this is displayed: http://screencast.com/t/texKc1ouXcxq

**Comment by komal-maru** [comment]
Currently, the latest version of WordPress plugin is 4.5.2 and it is showing the latest version when clicked on the View details: http://screencast.com/t/jdBX6kMWlT
