### ISSUE TITLE
Some strings are missing in .po file

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-delivery-date#105]
Some strings are missing in.po file
see the screenshot: 
https://www.screencast.com/t/GiulPcBWDP5
https://www.screencast.com/t/0nrHEFNym
https://www.screencast.com/t/Y3wLkxIqBptv
https://www.screencast.com/t/vHAX5dpOHKcF
https://www.screencast.com/t/2e1LAkesuCf
https://www.screencast.com/t/7x0mLBWCBSDC

We should add this string in .po file

**Comment by komal-maru** [comment]
Checked the screenshot: https://www.screencast.com/t/vHAX5dpOHKcF , this is product page which is not from our plugin.

**Comment by komal-maru** [comment]
The strings pointed: https://www.screencast.com/t/GiulPcBWDP5 , https://www.screencast.com/t/2e1LAkesuCf are the dynamic strings for which we have provided wpml-config.xml file. These strings can be translated through WPML plugin.

The strings pointed in this screenshot: https://www.screencast.com/t/7x0mLBWCBSDC , we are not allowing it to be translated which is also same in Pro version.
