### ISSUE TITLE
wrong selectable dates in calendar

### ISSUE THREAD

**Issue by stefanKBL** [TycheSoftwares/woocommerce-delivery-date#106]
hi, 
as an example, we are today 16 of february;
Wednesday and Saturday are checked as available days and 48 is the min delay.
No autopopulate and no holidays

So i should have 

- next saturday (17) unavailable : that's ok
- next wednesday (21) available : NOT AVAILABLE in calendar
- saturday 24 avalaible : that's ok
- and wedneday 28 available : that's ok

So what's going wrong with the 21 ?
Thanks

**Comment by moxajogani** [comment]
Could not replicate this issue with the latest version 3.6.1 of the plugin. Hence closing this issue.
