### ISSUE TITLE
Ability to add in "Your order" section

### ISSUE THREAD

**Issue by joshdanielsjr** [TycheSoftwares/woocommerce-delivery-date#109]
I have created some JS to populate the fields under the selected shipping method. However, the calendar is populating somewhere near the footer. Can you help me fix this issue? wazobiaafricanmarket.com

**Comment by Chetna1510** [comment]
-- Please reply above this line --


Hello Tychesoftwares/woocommerce-Delivery-Date,

We received your email request! Someone from our team will get back to
you as soon as possible.

Thank you!

**Comment by moxajogani** [comment]
I checked on the site and it seems he is using Pro version 7.6 on his site with some custom changes. Hence closing this issue now.
