### ISSUE TITLE
For some languages, the delivery date is not displayed correctly

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/woocommerce-delivery-date#12]
When the set langugage is Dutch, Bulgarian, Korean, Tamil, Turkish, Russian, Macedonian, etc the dates on the Orders page and Order Received page is coming with ‘?’ sign.

The set date format is Friday, November 20, 2015.

Dutch: http://screencast.com/t/pBvg7fF0eB4
Bulgarian: http://screencast.com/t/q5OehxSnQ8k

Orders page: (Russian language) http://screencast.com/t/VmR2LqdzC

**Comment by komal-maru** [comment]
Could not replicate the issue with the latest version which is 3.3.1

Tried to replicate it with Dutch, Russian language.

Russian: https://prnt.sc/i2zdws , https://prnt.sc/i2ze1h
Dutch: https://prnt.sc/i2zegp , https://prnt.sc/i2zejj , https://prnt.sc/i2zelv

Hence closing it.

**Comment by ashokrane** [comment]
Tested this with Tamil & Hungarian. Both worked fine.
