### ISSUE TITLE
Different delivery date could be added for renewal of Subscription

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/woocommerce-delivery-date#13]
With WooCommerce Subscriptions plugin, when the renewal email is sent, the checkout page from the Pay now link from the email, I am able to place the order by selecting another delivery date.

The actual order was placed for 6th Dec 2015. For the renewal, I could place the order for 11th Dec 2015.

Ideally if I select any other delivery date which is other than the actual order delivery date(here 6th Dec) when the order will be placed it will show the actual order's delivery date. (6th Dec)

**Comment by komal-maru** [comment]
When tried to place the order and renew the order using old version of WooCommerce Subscription plugin, the date is not getting updated. Where when tried to place renewal order in the latest version, the date is got updated.
