### ISSUE TITLE
Update welcome page is not coming

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-delivery-date#144]
After clearing database the update welcome page has not come
Updated version 3.4.2 to latest git copy
The dashboard and plugin page shows update notice but after click on Update welcome page has not come

**Comment by komal-maru** [comment]
I made a new local, then installed the 3.4.2 version of orddd lite then updated to the latest github copy the welcome page of update message comes. 

3.4.2: https://prnt.sc/k1mf1k
when updated to github copy: https://prnt.sc/k1mdzu

Could not replicate the issue, hence closing it.

**Comment by apeksha10** [comment]
Still. Update welcome page is not received
Steps: 1. Installed 3.4.2 version
2. Update notification comes on plugin page and dashboard-->Updates
3. Update plugin from Dashboard--> update
4. After Updating plugin Update welcome page not come
Hence re-open this issue

**Comment by apeksha10** [comment]
With latest git copy this issue is not replicate

Hence closed this issue
