### ISSUE TITLE
Holiday calendar goes out of line

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-delivery-date#146]
Set: Eggplant theme
Holiday calendar does not show properly
https://www.screencast.com/t/LfVGCK4dwug
https://www.screencast.com/t/VHSKa1ezQmJ2

**Comment by moxajogani** [comment]
Fixed with reference to commit: 86c9b788a96d129864cb63b7d563bf95fd04057f
Hence closing this issue.
