### ISSUE TITLE
Unable to add 2nd product to cart when our plugin is active

### ISSUE THREAD

**Issue by Dhara61** [TycheSoftwares/woocommerce-delivery-date#153]
This issue is replicated only as a customer login and not as a guest user or admin user.

He did some troubleshooting and shared this info:

**"i did a health check with the health check & troubleshooting plugin.
I lunch a test for individual plugin and Order delivery date for woocommerce (lite version) can't do the loopback.
Here the message: The loopback request to your site failed, this may prevent WP_Cron from working, along with theme and plugin editors.
Error encountered: (0) cURL error 28: Operation timed out after 10002 milliseconds with 0 bytes received"** 

https://tychesoftwares.freshdesk.com/a/tickets/5474

I tried replciating this issue on our local site as a customer but unable to replicate on our site.

**Comment by ashokrane** [comment]
@Dhara61 Has any other client told us about such an issue?

**Comment by Dhara61** [comment]
@ashokrane no, nobody has mentioned this issue apart from this client.

**Comment by moxajogani** [comment]
As this issue is not reported by any other client and the client is not using our plugin any more I am closing this issue for now. We will fix this issue is anyone else will report this.
