### ISSUE TITLE
All holidays are getting deleted when certain holidays are marked and in bulk action we try to delete them

### ISSUE THREAD

**Issue by Dhara61** [TycheSoftwares/woocommerce-delivery-date#156]
**Describe the bug**
All holidays are getting deleted when certain holidays are marked and in bulk action, we try to delete them. 

**To Reproduce**
1. Go to 'Holiday' tab.
2. Create 5-6 holidays
3. Then select 2-3 holidays from the list and delete it via bulk action 
4. all the holidays are getting deleted. 

**Expected behavior**
Ideally, the respective holidays only should get deleted. 

**Screenshots or Video**
https://drive.google.com/file/d/1VkcehbjNPJEV3m0mn9oj3ViwpZ_dX9cn/view 
https://prnt.sc/mdm0es
https://prnt.sc/mdm0ke

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome

**Isolating the problem (mark completed items with an [x]):**
- [x] This bug happens with only Order Delivery Date for WooCommerce plugin active
- [ x ] This bug happens with a default WordPress theme active, or [Storefront]
- [ x ] I can reproduce this bug consistently using the steps above

**Additional context**
Select at least 2 holidays for deleting via bulk action to replicate this issue.

**Comment by ashokrane** [comment]
@apeksha10 Are you able to replicate this?

**Comment by apeksha10** [comment]
yes.. I am able to replicate this issue with live copy

**Comment by apeksha10** [comment]
Yes. I am able to replicate this issue with live copy

**Comment by apeksha10** [comment]
With the latest git copy, still, I am able to replicate this issue. I try with above bulk action settings and Below Bulk action settings 
https://www.screencast.com/t/2g4RNFxnYm
see the video : https://www.screencast.com/t/aIArcddjVbW
Hence re-open this issue
