### ISSUE TITLE
Wrong delivery date comes on checkout page with Auto-populate settings is enable

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-delivery-date#158]
**Describe the bug**
Wrong delivery date on the checkout page.

**To Reproduce**
1. Set 'Lockout date after X orders' as 1
2. place an order for a particular date. (for example, the current date is 11-2-2019 Monday) 
3. Next weekdays is disabled for delivery ( Tuesday is disabled for delivery)
4. Check out page shows incorrect date

**Expected behavior**
Check out page should show a correct delivery date

**Screenshots or Video**
https://www.screencast.com/t/Ac1txnU6Z
https://www.screencast.com/t/MySU8eq6islz
https://www.screencast.com/t/6sdhlR8eoX
https://www.screencast.com/t/G9atUeBwT
https://www.screencast.com/t/bjDFYPokUY3

**Isolating the problem (mark completed items with an [x]):**
- [x] This bug happens with only Order Delivery Date for WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront]
- [x] I can reproduce this bug consistently using the steps above

**Additional context**
This issue replicate with Auto-populate settings are enabled

**Comment by apeksha10** [comment]
With the latest git copy the above issue fix but with other settings, a Delivery date on checkout page shows incorrect with AUto-populate settings enable

Steps to replicate: 1. Set lockout value 1
2. Only current weekdays is enabled for delivery ( in my case Thursday enable)
3. Minimum delivery time set as 48 hours
4. "Apply Minimum Delivery Time for nonworking weekdays" field is disabled
5.  Place order for the current day (4-4-2019)
6. Go to checkout page again then delivery calendar shows 25 April 2019 is first available for delivery which is wrong 
Ideally, the first available date comes 18 April

see the screenshot: https://www.screencast.com/t/OdQajUSCyq
https://www.screencast.com/t/egXwBKIEY
https://www.screencast.com/t/SDhjPGEMH

checkout page screenshot: https://www.screencast.com/t/Zoazeqzilc
https://www.screencast.com/t/3qFbuOPn

hence re-open this issue

**Comment by moxajogani** [comment]
The setup which @apeksha10 has mentioned should not allow placing an order for 4th April as the Minimum Delivery Time in hours is set as 48 hours. In this case, the first available date should be 18th April which is working fine for me. 

And even if an order is already placed earlier for 4th April and then Minimum Delivery Time is set, then the first available date should be 25th April only. 

So the issue is that 18th is coming available in the calendar which should not. 

@apeksha10 Can you please confirm?

**Comment by apeksha10** [comment]
Yes..I saw the settings the issue is that Minimum delivery time is not working with enable weekdays and "Apply Minimum Delivery Time for nonworking weekdays" field is disabled

hence closed this issue and put Fixed label
