### ISSUE TITLE
I am getting the error message when I upgraded WooCommerce. 

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/woocommerce-delivery-date#189]
**Describe the bug**
This issue is reported by the client.  I am also able to replicate the issue.

Once I have upgraded WooCommerce to the latest version, I am getting following error message on my staging site woo_chetna.

Notice: Undefined index: post_type in /home2/todaysa2/public_html/tychesoftwares/staging/woo_chetna/wp-content/plugins/order-delivery-date-for-woocommerce/order_delivery_date.php on line 97

Warning: Cannot modify header information - headers already sent by (output started at /home2/todaysa2/public_html/tychesoftwares/staging/woo_chetna/wp-content/plugins/order-delivery-date-for-woocommerce/order_delivery_date.php:97) in /home2/todaysa2/public_html/tychesoftwares/staging/woo_chetna/wp-admin/includes/misc.php on line 1198

**To Reproduce**
I have upgraded to the WooCommerce Version 3.6.1 from 3.5.7. And I noticed that the error message is showing on the checkout page.

Once I have deactivated our Order Delivery date LITE plugin, the error has gone away.
WooCommerce database is also updated and using storefront theme which is also up to date. http://prntscr.com/nf96vq

**Expected behavior**

**Screenshots or Video**
http://prntscr.com/nf84st

**Isolating the problem (mark completed items with an [x]):**
- [ x] This bug happens with only Order Delivery Date for WooCommerce plugin active
- [ x] This bug happens with a default WordPress theme active, or [Storefront]
- [x ] I can reproduce this bug consistently using the steps above

**WordPress Environment**
### WordPress Environment ###

Home URL: https://staging.tychesoftwares.com/woo_chetna 
Site URL: https://staging.tychesoftwares.com/woo_chetna 
WP Version: 5.1.1 
WP multisite: No 
WP debug mode: On 
WP Language: en-US 
WC Version: 3.6.1 
```
**Additional context**
Add any other context about the problem here.

**Comment by ashokrane** [comment]
@Chetna1510 This is coming in Lite or in Pro?

**Comment by Chetna1510** [comment]
In LITE. This issue has been informed by 2 clients.

**Comment by ashokrane** [comment]
@Chetna1510 They have both Lite & Pro versions active?

**Comment by Chetna1510** [comment]
@vishalck Only Lite plugin is activated. I am also able to replicate it on my staging and local as well.
