### ISSUE TITLE
Calendar not popping up on client site

### ISSUE THREAD

**Issue by Dhara61** [TycheSoftwares/woocommerce-delivery-date#193]
**Describe the bug**
On one of our client's site, the delivery calendar is not popping up. 

I switched the theme to StoreFront theme and things started working fine. But, this issue is not replicated on my local site even when the same theme is active, 

Also, the client confirmed that he is using this same theme on his staging site and it is working fine.

The important thing which client has mentioned "Our plugin is not working on the live site, but is working on the staging site where WordPress is not updated to the newest version.
It was the client that updated the Wordpress without knowing."

His site URL: https://byttevarmtvannsbereder.no/
Ticket URL: https://tychesoftwares.freshdesk.com/a/tickets/8506 
Link of the theme file: https://www.dropbox.com/sh/veo0zvq6y9mlkbu/AAA8LTp1FlX9CLS99Q4Yvvqqa?dl=0 

He is using the child theme. 

Error coming from our plugin: Failed to load resource: the server responded with a status of 404 ()
/wp-content/plugins/order-delivery-date-for-woocommerce/js/i18n/jquery.ui.datepicker-no.js%20defer%20onload=?ver=3.8.1:1 Failed to load resource: the server responded with a status of 404 ()

Screenshot: http://prntscr.com/nywr0h 

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/8506

**Comment by apeksha10** [comment]
I try to replicate the above issue on my local with the above theme but no luck
Tried to replicate the above issue on staging site where WordPress does not update, but the delivery date and delivery calendar work fine 
After updating Latest WordPress then too delivery date and delivery calendar works fine on checkout page
