### ISSUE TITLE
Past Delivery date enable when I put minus value in Minimum Delivery time (in hours):

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-delivery-date#208]
**Describe the bug**
Past Delivery date enable when I put minus value in Minimum Delivery time (in hours):

**To Reproduce**
1. I set -48 hours in Minimum Delivery time (in hours) filed
2. save the settings
3. go to checkout page and past date is enable for delivery which is wrong

Here as per my example : current date is 19th Aug and I set -48 hours in Minimum delivery time field then on checkout page shows 17 Aug enable for delivery and worst things is I am able to place the order for past date  

**Screenshots or Video**
https://www.screencast.com/t/320vDmDrY3L
https://www.screencast.com/t/Kd8rSS40MdV
https://www.screencast.com/t/awdvMf76lXH4
https://www.screencast.com/t/ooHAXZkZT4
https://www.screencast.com/t/WbYwLDv3

**Comment by moxajogani** [comment]
As we are not allowing a minus value in the field, this issue will not be valid (7747ec8ca795d7b63d30c7be49127363bf46870f) . Hence closing this.
