### ISSUE TITLE
Order Delivery Date Plugin Conflict with Latest Wordpress 5.5 Update

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/woocommerce-delivery-date#241]
**Describe the bug**
After updating Wordpress 5.5,the Visual/Text Editor is not working (non-clickable).

**To Reproduce**
1. Update WordPress to 5.5 on your site
2. On any page in the backend and you will see the TinyMCE editor is not working due to our plugin: https://prnt.sc/u1lza1

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/19658

**Comment by apeksha10** [comment]
The above same error replicates on the demo site after released the plugin.
I have updated the latest plugin copy and WC and WP.
see the screenshot : https://www.screencast.com/t/0nPbM0JBk

Note: The same issue is working fine on my localhost

Hence re-open this issue.

**Comment by apeksha10** [comment]
After clearing the cache, the above issues are not able to replicate on woo_apeksha.
