### ISSUE TITLE
Default time slot label shows as blank on the appearance tab.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-delivery-date#248]
**Describe the bug**
Default time slot label shows as blank on the appearance tab.

**To Reproduce**
1. After updating the latest git copy, on the Appearance tab the time slot field label shows as blank which is wrong.
we should give the default value as we did on delivery date field label. 

https://www.screencast.com/t/x7cgOHKrv

**Expected behavior**
The default time slot label should be present.

**Comment by rashmimalpande** [comment]
Fixed with pull request #252

**Comment by apeksha10** [comment]
In Fresh Installation testing, I am able to replicate the above issue

Steps to reproduced.
1. upload latest git copy ( Add New--Upload )
2. go to the time slot tab, the default time slot field label does not appear.
https://www.screencast.com/t/L5zdMKhc0

Note: this is working fine in an updated copy.

Re-opening this issue.
