### ISSUE TITLE
Delivery date are not getting block after changing the order status from Fail/Refund/cancelled to complete/Processing/on-hold.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-delivery-date#259]
**Describe the bug**
Delivery date are not getting block after changing the order status from Fail/Refund/cancelled to complete/Processing/on-hold.

**To Reproduce**
1. Date and time slot set up
2. Time slot lockout is set as 1. see the screenshot: https://www.screencast.com/t/WZrgf7dnMy0c
3. Place an order for the date of 2nd Sept. using Cash on Delivery. Now the 2nd Sept delivery date is getting blocked.
4. Now I change the order status Processing to fail, 2nd Sept released which is correct.
5. Again I changed the order status from Fail to on-hold/ complete then the delivery date is not getting block which is an issue
   https://www.screencast.com/t/ZZagiT9bXEdx, https://www.screencast.com/t/VuTBkKSlstX5

**Expected behavior**
The delivery date should be blocked after changing the order status Fail to Processing.

**Comment by rashmimalpande** [comment]
Fixed with pull request #261

**Comment by apeksha10** [comment]
Took latest git copy,
Steps to reproduce the above issue
1. date and time slot setup. https://www.screencast.com/t/DLdHfr1o1ZhW, https://www.screencast.com/t/DLdHfr1o1ZhW
2. Placing an order. https://www.screencast.com/t/oP1ZEihM8
3. The delivery date got blocked. https://www.screencast.com/t/DJ1cvpNYPm
4. change the order status from Processing to Fail. https://www.screencast.com/t/tr8UFNev3
5. again visit the same products checkout page, still, that delivery date is shows as a block. https://www.screencast.com/t/Ze7ZuVRRc   

other setup screenshots: https://www.screencast.com/t/Qt59Ta2jOc, https://www.screencast.com/t/EK5i0MFN
Hence re-open this issue.

**Comment by rashmimalpande** [comment]
The issue was coming when the time slot label was set to blank.
