### ISSUE TITLE
Word Array Appearing in Emails

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/woocommerce-delivery-date#271]
**Describe the bug**
In new order emails, the customer's requested delivery date is appended with an empty error or something ": Array".

**To Reproduce**
Not able to replicate at our end.

**Screenshots or Video**
https://prnt.sc/ubf9h7

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/20327

**Comment by rashmimalpande** [comment]
The issue was coming because the time slot label was not set after the update which resulted in this issue
