### ISSUE TITLE
The database update notice should not come when the plugin is freshly installed

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/woocommerce-delivery-date#34]
When the plugin is freshly installed on a website, the notice for updating the database is coming. This notice should not come on a fresh install.

http://screencast.com/t/4gNRXVUg4k

**Comment by komal-maru** [comment]
Database update notice has been removed in one of our plugin releases.

I didn't receive the update notice when freshly installed the plugin. Hence closing it.

**Comment by ashokrane** [comment]
Even I didn't receive a database update notice after installing 3.3.1. Marking Fixed.
