### ISSUE TITLE
Getting this error in debug.log file

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/woocommerce-delivery-date#36]
When our plugin is activated, I am getting this errors in debug.log file from WordPress.

> [11-Jul-2016 07:08:28 UTC] PHP Notice:  map_meta_cap was called <strong>incorrectly</strong>. The post type scheduled-action is not registered, so it may not be reliable to check the capability "edit_post" against a post of that type. Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 4.4.0.) in /home/tychesod/public_html/staging/woo_khyati2/wp-includes/functions.php on line 3897

When the plugin is deactivated the error is not coming on placing the order.

**Comment by komal-maru** [comment]
Replicated the issue once. But, now I am unable to replicate it with the live version (3.3.1) directly downloaded from WordPress.org site and also with the github copy (23 Jan,2018).

In future, we might find proper steps, scenarios to replicate this issue and we will be able to fix it then.

Currently, closing it as I could not replicate it.

**Comment by ashokrane** [comment]
Looks fine. I didn't get this error in debug log. I created the plugin settings, added holidays & placed an order. I didn't find this appearing in the error log. Hence marking as Fixed.
