### ISSUE TITLE
Number of dates is coming wrong

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/woocommerce-delivery-date#39]
Number of dates to choose is set to 30, but there are 31 dates available for delivery.

**Comment by komal-maru** [comment]
Checked with the latest version:3.3.1

Checked by setting the 'Number of dates to choose' to 30, and 30 days were available in the calendar.
Setting: https://prnt.sc/i2zoia
checkout: https://prnt.sc/i2zol5 , https://prnt.sc/i2zomr

When 'Number of dates to choose' is set to 10, the number of dates r shown fine as per the set setting.

Hence closing the issue.

**Comment by ashokrane** [comment]
This works fine now. Number of dates to choose was set to 60. And it showed me 58 enabled dates as 2 were locked out. I then increased the lockout value. It showed me same 60 dates, including those 2 locked out dates as well for selecting.
