### ISSUE TITLE
Date format is not come properly

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-delivery-date#62]
When i select date format as dd-mm-yy in Appearance tab--Date format then Holiday tab shows wrong format that is mm-dd-yy.
https://www.screencast.com/t/6FZd8Xsa
https://www.screencast.com/t/vAFRghSUikL

If i select 21 March 2017 format then also it shows wrong format.
https://www.screencast.com/t/2S45gUew5
https://www.screencast.com/t/PQhl3eZqD

**Comment by komal-maru** [comment]
The format set for the Date Format option will not be reflected on Holidays in the Holidays tab, it will be only shown on the front end, WooCommerce->Orders page, email, Order Received page.

**Comment by ashokrane** [comment]
Although it's not necessary for the date format in Admin to be same as that of the frontend date format, but it would be nice if the date format of admin holidays & elsewhere is mentioned as placeholder in the field. Adding this as a new issue under enhancements.
