### ISSUE TITLE
The date is not coming as per the set language on the order received page

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/woocommerce-delivery-date#64]
The language of the delivery calendar is set to German, On the checkout page, the calendar is coming in the selected language. But on placing the order the delivery date is coming in English and not in the selected delivery language.

Checkout page: http://prnt.sc/enfczs
Order Received page: http://prnt.sc/enfdgz

**Comment by komal-maru** [comment]
Could not replicate the issue on the staging site with the latest version of the WooCommerce plugin which is v3.1. Hence closing it.
