### ISSUE TITLE
Wrong Delivery Date is auto-populated, not considering the disabled days.

### ISSUE THREAD

**Issue by komal-maru** [TycheSoftwares/woocommerce-delivery-date#68]
I have set up Monday, Thursday, Friday, Saturday, Sunday Minimum Delivery time is set to 24 hours.

'Auto-populate first available Delivery date' is enabled and the 'Apply Minimum Delivery Time for non working weekdays' setting is enabled.

Then when I visit the site on Tuesday 4th July, 2017, 5th July, 2017 is auto-populated whereas it is disabled for delivery.

I am attaching screenshots of the settings: http://prntscr.com/frglm5 , http://prntscr.com/frglqt , http://prntscr.com/frglwl , http://prntscr.com/frgm5s

**Comment by komal-maru** [comment]
Closed in the other issue. Reference link: e39a2155e590780c29e86252547d10e904bb42b4

**Comment by ashokrane** [comment]
Today's date: 24 January - Wednesday
Delivery days disabled; Thursday, Monday
Min. Delivery time: 48 hours
Autopopulate: on
Apply Minimum Delivery Time for non working weekdays: on

The auto-populated date shown in this case is 27th January, but 26th January should be shown. The date of 26th January is still enabled & valid for selection, but just that it doesn't appear autopopulated. That needs to be fixed.

**Comment by komal-maru** [comment]
Could not replicate with the github copy 28 June, 2018.

Settings: https://prnt.sc/k0emhb

I visited the site on 28 June, 2018, the first available date is 30 June which is the correct date as per the settings set.
