### ISSUE TITLE
On updating the plugin the orddd menu page is giving a warning saying insufficient permission

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/woocommerce-delivery-date#7]
When a lite version user has the orddd menu page opened, updates the plugin from the WordPress plugins page and then refreshes the orddd menu page, that is when the user gets insufficient permission to access the page warning. http://screencast.com/t/jhLUxtLY

This will confuse the user and may think that the update broke the plugin.

This is happenening becose we have changed the page name. Ealier path was: 'http://localhost/wordpress/wp-admin/admin.php?page=order_delivery_date' and the new one is at: 'http://localhost/wordpress/wp-admin/admin.php?page=order_delivery_date_lite'. Hence we should redirect the old path to the new page name when the user accesses the old page.

**Comment by komal-maru** [comment]
This is a very rare scenario where the users will access the menu using the links. They access using the WordPress admin menu. Can be fixed in next version.

**Comment by komal-maru** [comment]
We can fix this issue by redirecting the path from 'http://localhost/wordpress/wp-admin/admin.php?page=order_delivery_date' to 'http://localhost/wordpress/wp-admin/admin.php?page=order_delivery_date_lite'. 

But there is a case when a client uses both lite and Pro version plugin and the client tries to access the Pro's Order Delivery Date menu at that time the client will be redirected to Lite's Order Delivery Date menu. 

As this a rare case, we can close this issue without fixing it.
