### ISSUE TITLE
Delivery date is not comes proper when Apply Minimum Delivery Time for non working weekdays field is enable. 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-delivery-date#72]
Here i enable "Apply Minimum Delivery Time for non-working weekdays" and "Auto-populate first available Delivery date" both field.
I disable Thursday for delivery and i visit the site on Wednesday.The Minimum Delivery time (in hours) is set 24 hours.
Now i go to the front end of the product it shows 6 July 2017 on delivery date field which is disabled for delivery.

Screenshot of front end :https://www.screencast.com/t/52LqwvE2iz9t
Screenshot of setting page: https://www.screencast.com/t/1Twtv43CV9

**Comment by ashokrane** [comment]
This works fine.
