### ISSUE TITLE
Holiday tab shows past date available

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-delivery-date#89]
I am testing with WordPress beta version 4.9-RC2 copy
When i set any holiday then holiday file shows past date available

Today is 11-11-2017 date https://www.screencast.com/t/2Bvrzvi25jD

**Comment by komal-maru** [comment]
After discussing with sir, Sir told to keep as it is where the past dates are also available in the holidays calendar under the Holidays tab.

Because it might be the case where the admin wants to add the past dates as holidays just for record purpose.

Hence closing it.
